### ISSUE TITLE
Missing `public init(){}`: _'Bubble' initializer is inaccessible due to 'internal' protection level_

### ISSUE THREAD

**Issue by janekb04** [c-villain/Shapes#5]
The provided example doesn't compile.

<img width="676" alt="29 04 2023 @ 0054 46@2x" src="https://user-images.githubusercontent.com/13035076/235266659-d9c4df0b-18f4-446b-bfe2-2652580f7658.png">

I found that [this](https://stackoverflow.com/questions/40859139/initializer-is-inaccessable-due-to-internal-protection-level) should work. As a workaround, I `@testable import Shapes`.

**Comment by c-villain** [comment]
@janekb04 fixed in [0.2.1](https://github.com/c-villain/Shapes/releases/tag/0.2.1)
